trueque_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tt_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tt_app/urls.py
from django.urls import path
from .views import (
    producto_view,
    usuario_view,
    trueque_view,
    venta_view,
    sucursal_view,
    estadistica_view,
)

urlpatterns = [
    path("", usuario_view.home, name="home"),
    path("registro/", usuario_view.registro, name="registro"),
    path("ingreso/", usuario_view.ingreso, name="ingreso"),
    path("logout/", usuario_view.cerrar_sesion, name="logout"),
    path("crear_producto/", producto_view.crear_producto, name="crear_producto"),
    path(
        "modificar_producto/<int:id>",
        producto_view.modificar_producto,
        name="modificar_producto",
    ),
    path(
        "eliminar_producto/<int:id>",
        producto_view.eliminar_producto,
        name="eliminar_producto",
    ),
    path("productos/", producto_view.productos, name="productos"),
    path("buscar_productos/", producto_view.buscar_productos, name="buscar_productos"),
    path(
        "buscar_productos_trueques_programados/",
        producto_view.buscar_productos_trueques_programados,
        name="buscar_productos_trueques_programados",
    ),
    path(
        "productos/id/<int:id>", producto_view.detalle_producto, name="detalle_producto"
    ),
    path(
        "registro_empleado/", usuario_view.registro_empleado, name="registro_empleado"
    ),
    path(
        "trueques_entrantes/",
        trueque_view.trueques_entrantes,
        name="trueques_entrantes",
    ),
    path(
        "aceptar-solicitud/<int:trueque_id>/",
        trueque_view.aceptar_solicitud,
        name="aceptar-solicitud",
    ),
    path(
        "rechazar-solicitud-interes/<int:trueque_id>/",
        trueque_view.rechazar_solicitud_interes,
        name="rechazar-solicitud-interes",
    ),
    path(
        "rechazar-solicitud-horario/<int:trueque_id>/",
        trueque_view.rechazar_solitud_horario,
        name="rechazar-solicitud-horario",
    ),
    path(
        "rechazar-solicitud-fecha/<int:trueque_id>/",
        trueque_view.rechazar_solicitud_fecha,
        name="rechazar-solicitud-fecha",
    ),
    path(
        "rechazar-solicitud-otros/<int:trueque_id>/",
        trueque_view.rechazar_solicitud_otros,
        name="rechazar-solicitud-otros",
    ),
    path(
        "cancelar_trueque/<int:id>/<int:estado>/<str:ret>",
        trueque_view.cancelar_trueque,
        name="cancelar_trueque",
    ),
    path("solicitar/<int:id>/", trueque_view.solicitar, name="solicitar"),
    path("trueque/id/<int:id>", trueque_view.detalle_trueque, name="detalle_trueque"),
    path(
        "trueques_salientes/",
        trueque_view.trueques_salientes,
        name="trueques_salientes",
    ),
    path(
        "trueques_por_concretar/",
        trueque_view.trueques_por_concretar,
        name="trueques_por_concretar",
    ),
    path(
        "trueques_finalizados/",
        trueque_view.trueques_finalizados,
        name="trueques_finalizados",
    ),
    path("productos/id/<int:id>/preguntar", producto_view.preguntar, name="preguntar"),
    path("productos/id/<int:id>/responder", producto_view.responder, name="responder"),
    path(
        "filtrar_productos/<int:categoria>",
        producto_view.filtrar_productos,
        name="filtrar_productos",
    ),
    path("mis_productos/<int:id>", producto_view.mis_productos, name="mis_productos"),
    path("empleados", usuario_view.listado_empleados, name="empleados"),
    path(
        "trueques_programados/",
        trueque_view.trueques_programados,
        name="trueques_programados",
    ),
    path(
        "trueques_concretados/",
        trueque_view.trueques_concretados,
        name="trueques_concretados",
    ),
    path(
        "registrar-ventas/<int:trueque_id>",
        venta_view.registrar_ventas,
        name="registrar_ventas",
    ),
    path(
        "concretar-trueque/<int:trueque_id>/",
        trueque_view.confirmar_trueque,
        name="concretar_trueque",
    ),
    path(
        "listar-ventas-trueque/<int:trueque_id>",
        venta_view.listar_ventas,
        name="listar_ventas_trueque",
    ),
    path(
        "cancelar-trueques-programados/",
        trueque_view.cancelar_trueque_programado,
        name="cancelar_trueques_programados",
    ),
    path("sucursales/", sucursal_view.listado_sucursales, name="sucursales"),
    path(
        "promocionar-producto/<int:id>",
        producto_view.promocionar,
        name="promocionar_producto",
    ),
    path(
        "modificar_empleado/<int:id>/",
        usuario_view.modificar_empleado,
        name="modificar_empleado",
    ),
    path(
        "eliminar_empleado/<int:id>/",
        usuario_view.eliminar_empleado,
        name="eliminar_empleado",
    ),
    path("crear-sucursal/", sucursal_view.crear_sucursal, name="crear_sucursal"),
    path(
        "modificar_sucursal/<int:id>/",
        sucursal_view.modificar_sucursal,
        name="modificar_sucursal",
    ),
    path(
        "eliminar_sucursal/<int:id>/",
        sucursal_view.eliminar_sucursal,
        name="eliminar_sucursal",
    ),
    path(
        "generar_estadisticas_ventas",
        estadistica_view.generar_estadisticas_ventas,
        name="generar_estadisticas_ventas",
    ),
    path(
        "generar_estadisticas_trueques",
        estadistica_view.generar_estadisticas_trueques,
        name="generar_estadisticas_trueques",
    ),
]

tt_app/models.py
from django.db import models
from django.db.models.fields.files import ImageField
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from datetime import datetime


# Create your models here.
# Creating users and superusers


# Modelo de sucursal
class Sucursal(models.Model):
    ciudad = models.CharField(max_length=50)
    direccion = models.CharField(max_length=200)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.ciudad + " - " + self.direccion


class MyCustomUserManager(BaseUserManager):
    def create_cliente(
        self, email, first_name, last_name, dni, phone, birthdate, password=None
    ):
        if not email:
            raise ValueError("El nombre de usuario debe ser tu correo electrónico.")
        cliente = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            dni=dni,
            phone=phone,
            birthdate=birthdate,
        )
        cliente.set_password(password)
        cliente.save(using=self._db)
        return cliente

    def create_empleado(self, email, first_name, last_name, password, sucursal):
        if not email:
            raise ValueError("El nombre de usuario debe ser tu correo electrónico.")
        empleado = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            sucursal=sucursal,
        )
        empleado.is_staff = True
        empleado.set_password(password)
        empleado.save(using=self._db)
        return empleado

    def create_superuser(self, email, password):
        user = self.create_cliente(
            email=self.normalize_email(email),
            first_name="",
            last_name="",
            dni="",
            phone="",
            birthdate="1900-01-01",
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        # user.is_superuser = True #Comento esta línea porque no tendría que tener permitido el acceso al panel de administración de django
        user.save(using=self._db)
        return user


# User model
class Usuario(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, blank=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    dni = models.CharField(max_length=10, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    birthdate = models.DateField(default="1990-01-01", blank=True)
    hide_email = models.BooleanField(default=True)
    sucursal = models.ForeignKey(
        Sucursal, on_delete=models.CASCADE, related_name="empleados", null=True
    )

    objects = MyCustomUserManager()

    USERNAME_FIELD = "email"

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


# Product model
class Producto(models.Model):

    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(
        validators=[
            MinLengthValidator(10, "Este campo debe contener al menos 10 caracteres")
        ],
        max_length=1000,
    )

    class Categoria(models.IntegerChoices):
        categoria_1 = 1, _("$0-$4999")
        categoria_2 = 2, _("$5000-$9999")
        categoria_3 = 3, _("$10000+")

    categoria = models.IntegerField(choices=Categoria.choices)
    fecha_de_publicacion = models.DateTimeField(auto_now=False)

    imagen = ImageField(blank=True, upload_to="media/")
    promocionado = models.BooleanField(default=False)
    reservado = models.BooleanField(default=False)
    disponible = models.BooleanField(default=True)
    activo = models.BooleanField(default=True)
    usuario = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, related_name="productos"
    )
    sucursal = models.ForeignKey(
        Sucursal, on_delete=models.CASCADE, related_name="productos"
    )
    fecha_hasta_promocion = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.nombre + "\t(" + str(self.categoria) + ")"


# Modelo de trueque
class Trueque(models.Model):
    producto_solicitante = models.ForeignKey(
        Producto,
        on_delete=models.CASCADE,
        related_name="trueque",
        null=False,
        blank=False,
    )
    producto_solicitado = models.ForeignKey(
        Producto,
        on_delete=models.CASCADE,
        related_name="trueque_solicitado",
        null=False,
        blank=False,
    )
    sucursal = models.ForeignKey(
        Sucursal,
        on_delete=models.CASCADE,
        related_name="trueques",
        null=False,
        blank=False,
    )
    activo = models.BooleanField(default=True)
    fecha = models.DateField(auto_now=True)
    fecha_programada = models.DateField(default="2025-01-01", blank=True)

    class Rango_Horario(models.IntegerChoices):
        rango_1 = 1, _("Turno Mañana: 8 AM")
        rango_2 = 2, _("Turno Mañana: 9 AM")
        rango_3 = 3, _("Turno Mañana: 10 AM")
        rango_4 = 4, _("Turno Mañana: 11 AM")
        rango_5 = 5, _("Turno Tarde: 3 PM")
        rango_6 = 6, _("Turno Tarde: 4 PM")
        rango_7 = 7, _("Turno Tarde: 5 PM")
        rango_8 = 8, _("Turno Tarde: 6 PM")
        rango_9 = 9, _("Turno Tarde: 7 PM")

    horario = models.IntegerField(
        choices=Rango_Horario.choices, blank=False, null=False, default=1
    )

    class Estado(models.IntegerChoices):
        estado_1 = 1, _("Solicitado")
        estado_2 = 2, _("Pendiente")
        estado_3 = 3, _("Aceptado")
        estado_4 = 4, _("Concretado")
        estado_5 = 5, _("Rechazado")
        estado_6 = 6, _("Cancelado por empleado")
        estado_7 = 7, _("Cancelado por solicitante")
        estado_8 = 8, _("Cancelado por solicitado")
        estado_9 = 9, _("Concretó otro trueque")

    estado = models.IntegerField(choices=Estado.choices, default=1)

    class OpcionRechazo(models.IntegerChoices):
        rechazo_1 = 1, _("Producto ya no disponible")
        rechazo_2 = 2, _("Falta de interés en el producto ofrecido")
        rechazo_3 = 3, _("Falta de disponibilidad en el horario solicitado")
        rechazo_4 = 4, _("Falta de disponibilidad en la fecha solicitada")
        rechazo_5 = 5, _("Otros motivos")

    motivo_rechazo = models.IntegerField(
        choices=OpcionRechazo.choices, blank=True, null=True, default=None
    )

    def __str__(self):
        p1 = self.producto_solicitante
        p2 = self.producto_solicitado
        return (
            "("
            + str(self.id)
            + ")  "
            + p1.usuario.first_name
            + " quiere intercambiar "
            + p1.nombre
            + " por "
            + p2.nombre
            + " de "
            + p2.usuario.first_name
        )


# Modelo de respuesta
class Respuesta(models.Model):
    texto = models.CharField(max_length=200)
    fecha = models.DateField(auto_now=True)
    activo = models.BooleanField(default=True)


# Modelo de pregunta
class Pregunta(models.Model):
    producto = models.ForeignKey(
        Producto, on_delete=models.CASCADE, related_name="preguntas"
    )
    cliente = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    respuesta = models.ForeignKey(Respuesta, on_delete=models.CASCADE, null=True)
    fecha = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)


# Modelo de venta
class Venta(models.Model):
    cantidad_unidades = models.IntegerField()
    precio_unitario = models.FloatField()
    nombre_producto = models.CharField(max_length=200)
    trueque = models.ForeignKey(
        Trueque, on_delete=models.CASCADE, blank=True, null=True
    )
    vendedor = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, blank=True, null=True
    )
    fecha = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)

    def get_total(self):
        return self.cantidad_unidades * self.precio_unitario

tt_app/views/sucursal_view.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from ..forms.sucursal_forms import CrearSucursal
from ..forms.usuario_forms import check_cliente, check_empleado, check_administrador
from ..models import Sucursal
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import get_object_or_404


def listado_sucursales(request):
    sucursales = Sucursal.objects.filter(activo=True)
    return render(request, "sucursales/sucursales.html", {"sucursales": sucursales})


def crear_sucursal(request):
    chk = check_administrador(request.user)
    if chk["ok"]:
        return chk["return"]
    if request.POST:
        form = CrearSucursal(request.POST)
        if form.is_valid():
            sucursal = form.save(commit=False)
            # sucursal.ciudad = sucursal.ciudad.capitalize()
            sucursal.save()  # guardamos el producto
            # Redirigir a la página de productos con mensaje de feedback
            return redirect(
                reverse("sucursales")
                + "?mensaje=La sucursal se ha agregado correctamente."
            )
    else:
        form = CrearSucursal()
    return render(
        request,
        "sucursales/crear_sucursal.html",
        {  # enviamos los siguientes parámetros:
            "form": form,  # el form definido en producto_forms.py
            "titulo": "Registrar sucursal",  # el titulo del form
            "boton": "Aceptar",  # el texto del botón de confirmación
            "obligatorios": True,  # mostrar la advertencia de campos obligatorios o no
        },
    )


@login_required
def modificar_sucursal(request, id):
    chk = check_administrador(request.user)
    if chk["ok"]:
        return chk["return"]

    sucursal = get_object_or_404(Sucursal, id=id)

    if request.method == "POST":
        form = CrearSucursal(request.POST, request.FILES, instance=sucursal)
        if form.is_valid():
            form = form.save(commit=False)
            print("modificando...")
            form.save()
            # Redirigir a la página de las sucursales con mensaje de feedback
            return redirect(
                reverse("sucursales")
                + "?mensaje=La sucursal se ha modificado correctamente."
            )
    else:
        form = CrearSucursal(instance=sucursal)

    return render(
        request,
        "sucursales/crear_sucursal.html",
        {
            "form": form,
            "titulo": "Modificar sucursal",
            "boton": "Modificar",
            "obligatorios": False,
        },
    )


@login_required
def eliminar_sucursal(request, id):
    chk = check_administrador(request.user)
    if chk["ok"]:
        return chk["return"]

    sucursal = get_object_or_404(Sucursal, id=id)

    if request.method == "POST":
        sucursal.activo = False
        sucursal.save()
        return redirect(
            reverse("sucursales")
            + "?mensaje=La sucursal se ha eliminado correctamente."
        )
    else:
        # Redirigir a la página de las sucursales con mensaje de feedback
        return redirect(
            reverse("sucursales") + "?mensaje=La sucursal no se ha podido eliminar."
        )

tt_app/templates/trueques/detalle_trueque.html
{%extends 'base.html'%}

{% load static %}
{%block content%}
{%if trueque.estado == 4%}
<div class="card border border-2 p-4">
    <h4 class="card-title my-4 text-center text-primary fs-2">Intercambio concretado <br><small>{{trueque.producto_solicitante.nombre|capfirst}} por {{trueque.producto_solicitado.nombre|capfirst}}</small></h4>
    <div class="d-flex align-items-center justify-content-evenly p-2 text-center">
        <div class="d-flex flex-column  col-5">
            <div class="d-flex mb-2" style="height:350px;">
                <img src="{%if trueque.producto_solicitante.imagen%}
                        {{trueque.producto_solicitante.imagen.url}}
                        {%else%}
                        {% static 'images/default-image-missing.png' %}
                        {%endif%}" 
                        class="img-fluid rounded mh-100 m-auto border border-3 border-primary " 
                        alt="Producto de {{trueque.producto_solicitante.usuario.first_name}}">
            </div>
            
            <p class="mb-1 fw-medium">{{trueque.producto_solicitante.usuario.first_name|capfirst}}</p>
            <p class="text-muted">{{trueque.producto_solicitante.nombre|capfirst}}</p>
        </div>
        <div class="d-flex col-2 align-items-center justify-content-center">
            <h1><span class="material-symbols-outlined text-primary" style="font-size:60px;">sync_lock</span></h1>
        </div>
        <div class="d-flex flex-column  col-5">
            <div class="d-flex mb-2" style="height:350px;">
                <img src="{%if trueque.producto_solicitado.imagen%}
                        {{trueque.producto_solicitado.imagen.url}}
                        {%else%}
                        {% static 'images/default-image-missing.png' %}
                        {%endif%}" 
                        class="img-fluid rounded mh-100 m-auto  border border-3 border-primary " 
                        alt="Producto de {{trueque.producto_solicitado.usuario.first_name}}">
            </div>
            <p class="mb-1 fw-medium">{{trueque.producto_solicitado.usuario.first_name|capfirst}}</p>
            <p class="text-muted">{{trueque.producto_solicitado.nombre|capfirst}}</p>
        </div>
    </div>
    <div class="row mt-3 p-2 text-center ">
        <p class="fs-5 "><span class="fw-light">SUCURSAL DONDE SE LLEVÓ A CABO: {{trueque.sucursal|upper}}</span></p>
        <p class="fs-5 mb-4 fw-light">SE CONCRETÓ EL DÍA {{trueque.fecha|date:'j \D\E F \D\E Y'|upper}}</p>
        
        {%if ventas%}
        <p class="fs-3">-VENTAS-</p>
        {%else%}
        <p class="fs-5 text-muted">-NO SE REGISTRARON VENTAS-</p>
        {%endif%}
    </div>
    {%include 'ventas/partials/partial_listado_ventas.html'%}
</div>
{%else%}
    <h5 class="mt-5 my-3 text-center">Este trueque no ha sido concretado.</h5> 
    <p class="p-2 text-center"><a href="{%url 'home'%}">Volver al inicio</a></p>
{% endif %}
{%endblock%}

tt_app/templates/trueques/solicitar.html
{% extends 'base.html' %}

{% block content %}

{% include 'partials/form_vista.html'%}

{% endblock %}

tt_app/templates/trueques/trueques_concretados.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if trueques %}
    <h3 class="ms-4 mt-2 mb-4 text-start ">Trueques concretados: </h3>
    
    {% for trueque in trueques %}
    {%if trueque.estado == 4%}  {#concretado#} 
    <div class="card d-flex mb-3 ms-4 border border-2 border-primary  bg-opacity-10">
    {%else%} {#rechazado o cancelado#}
    <div class="card d-flex mb-3 ms-4 border border-2 border-danger  bg-danger bg-opacity-10">
    {%endif%}
        <div class="row p-2" style="height:250px;">
            <div class="container col-lg-5 d-flex m-auto mh-100">
                <div class="col-lg-5 d-flex flex-column align-items-center justify-content-center ">
                    <a href="{% url 'detalle_producto' trueque.producto_solicitado.id%}" class="d-flex" style="height:190px;">
                        <img src="
                        {%if trueque.producto_solicitado.imagen%}
                        {{trueque.producto_solicitado.imagen.url}}
                        {%else%}
                        {% static 'images/default-image-missing.png' %}
                        {%endif%}" alt="img" class="img-fluid rounded mh-100 m-auto  border  
                        {%if trueque.estado == 4%}{#concretado#}border-primary
                        {%else%} {#rechazado o cancelado#}border-danger 
                        {%endif%}
                        ">
                    </a>
                    <small class="text-muted">{{trueque.producto_solicitado.usuario.first_name}}</small>
                </div>
                <div class="col-lg-2 d-flex my-auto">{#icono#}
                    {%if trueque.estado > 4%}
                    <span class="material-symbols-outlined mx-auto text-danger">sync_disabled</span>
                    {%else%}
                    <span class="material-symbols-outlined mx-auto text-primary">sync_lock</span>
                    {%endif%}
                </div>
                <div class="col-lg-5 d-flex flex-column align-items-center justify-content-center">
            
                    <a href="{% url 'detalle_producto' trueque.producto_solicitante.id%}" class="d-flex"style="height:190px;">
                        <img src="
                        {%if trueque.producto_solicitante.imagen%}
                        {{trueque.producto_solicitante.imagen.url}}
                        {%else%}
                        {% static 'images/default-image-missing.png' %}
                        {%endif%}" alt="{{trueque.producto_solicitante.usuario.first_name}} producto" class="img-fluid rounded mh-100 m-auto  border  
                        {%if trueque.estado == 4%}{#concretado#}border-primary
                        {%else%}{#rechazado o cancelado#}border-danger 
                        {%endif%}
                        ">
                    </a>
                    <small class="text-muted">{{trueque.producto_solicitante.usuario.first_name}}</small>
                </div>
            </div>
            <div class="card-body col-lg-7 d-flex flex-column ">

                <h4 class="card-title my-2 mb-2 {%if trueque.estado > 4%}text-danger{%else%}text-primary{%endif%}"><a href="{% url 'detalle_trueque' trueque.id%}" class="text-decoration-none text-reset">
                    Intercambio de {{trueque.producto_solicitante.nombre|striptags|truncatechars:40}} por {{trueque.producto_solicitado.nombre|striptags|truncatechars:40}}</a>
                </h4>

                {%if trueque.estado == 4%} 
                <p class="card-title text-primary my-4">Se confirmó el trueque exitosamente!</p>
                {%elif trueque.estado == 9%}
                <p class="card-title text-danger my-4">{{trueque.producto_solicitado.usuario.first_name|title}} {{trueque.get_estado_display|lower}} por su {{trueque.producto_solicitado.nombre}}.</p>
                {%elif trueque.estado == 5%}
                <p class="card-title text-danger my-4">RECHAZADO: {{trueque.get_motivo_rechazo_display}}</p>
                {%elif trueque.estado == 7%}
                <p class="card-title text-danger my-4">
                    {%if request.user == trueque.producto_solicitante.usuario%}
                    Cancelaste este trueque.
                    {%else%}
                    Cancelado por {{trueque.producto_solicitante.usuario.first_name|title}}.
                    {%endif%}
                </p>
                {%elif trueque.estado == 8%}
                <p class="card-title text-danger my-4">
                    {%if request.user == trueque.producto_solicitado.usuario%}
                    Cancelaste este trueque.
                    {%else%}
                    Cancelado por {{trueque.producto_solicitado.usuario.first_name|title}}.
                    {%endif%}
                </p>
                {%else%}
                <p class="card-title text-danger my-4">{{trueque.get_estado_display}}.</p>
                {%endif%}

                <span class="card-text d-flex ">
                    <div class="d-flex flex-column me-auto">
                        <small class="fw-light"><b>Sucursal</b>: {{trueque.sucursal}}</small>
                        <small class="fw-light"><b>Fecha</b>: {{trueque.fecha_programada|date:'l j \d\e F, Y'|capfirst}}</small>
                        <small class="fw-light"><b>Horario</b>: {{trueque.get_horario_display}}</small>
                    </div>
                </span>
            </div>
        </div>
    </div>

    {%endfor%}




{% else %}
    <h5 class="mt-5 my-3 text-center">No tiene trueques concretados por hoy.</h5> 
    <p class="p-2 text-center"><a href="{%url 'home'%}">Volver al inicio</a></p>
{% endif %}

{%endblock%}

tt_app/templates/trueques/trueques_entrantes.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if trueques %}
<h3 class="ms-4 mt-3 mb-5 text-start ">Solicitudes de trueques recibidas: </h3>
{% include 'trueques/partials/listado_trueques_entrantes.html' %}

{% else %}
    <h5 class="mt-5 my-3 text-center">No tiene solicitudes de trueque recibidas.</h5> 
    <p class="p-2 text-center"><a href="{%url 'home'%}">Volver al inicio</a></p>
{% endif %}

{%endblock%}

tt_app/templates/trueques/trueques_finalizados.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if trueques %}
    <h3 class="ms-4 mt-3 mb-5 text-start ">Trueques finalizados: </h3>
    {% include 'trueques/partials/listado_trueques_finalizados.html' %}

{% else %}
    <h5 class="mt-5 my-3 text-center">No tiene trueques finalizados.</h5> 
    <p class="p-2 text-center"><a href="{%url 'home'%}">Volver al inicio</a></p>
{% endif %}

{%endblock%}

tt_app/templates/trueques/trueques_por_concretar.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if trueques %}
    <h3 class="ms-4 mt-3 mb-5 text-start ">Trueques por concretar: </h3>
    {% include 'trueques/partials/listado_trueques_por_concretar.html' %}
{% else %}
    <h5 class="mt-5 my-3 text-center">No tiene trueques por concretar.</h5> 
    <p class="p-2 text-center"><a href="{%url 'home'%}">Volver al inicio</a></p>
{% endif %}

{%endblock%}

tt_app/templates/trueques/trueques_programados.html
{%extends 'base.html'%}

{% load static %}
{% include "trueques/partials/navbar_empleado.html" %}
{%block content%}

{% if trueques %}
    
    {% include 'trueques/partials/listado_trueques_programados.html' %}
   
{% else %}
    
    <h5 class="mt-5 my-3 text-center">No tiene trueques programados para hoy.</h5>
    <p class="p-2 text-center"><a href="{% url 'home' %}">Volver al inicio</a></p>
{% endif %}
{% endblock %}

tt_app/templates/trueques/trueques_salientes.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if trueques %}
    <h3 class="ms-4 mt-3 mb-5 text-start ">Solicitudes de trueque enviadas: </h3>
    {% include 'trueques/partials/listado_trueques_salientes.html' %}

{% else %}
    <h5 class="mt-5 my-3 text-center">No tiene solicitudes de trueque enviadas.</h5> 
    <p class="p-2 text-center"><a href="{%url 'home'%}">Volver al inicio</a></p>
{% endif %}

{%endblock%}