trueque_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tt_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tt_app/urls.py
from django.urls import path
from .views import (
    producto_view,
    usuario_view,
    trueque_view,
    venta_view,
    sucursal_view,
    estadistica_view,
)

urlpatterns = [
    path("", usuario_view.home, name="home"),
    path("registro/", usuario_view.registro, name="registro"),
    path("ingreso/", usuario_view.ingreso, name="ingreso"),
    path("logout/", usuario_view.cerrar_sesion, name="logout"),
    path("crear_producto/", producto_view.crear_producto, name="crear_producto"),
    path(
        "modificar_producto/<int:id>",
        producto_view.modificar_producto,
        name="modificar_producto",
    ),
    path(
        "eliminar_producto/<int:id>",
        producto_view.eliminar_producto,
        name="eliminar_producto",
    ),
    path("productos/", producto_view.productos, name="productos"),
    path("buscar_productos/", producto_view.buscar_productos, name="buscar_productos"),
    path(
        "buscar_productos_trueques_programados/",
        producto_view.buscar_productos_trueques_programados,
        name="buscar_productos_trueques_programados",
    ),
    path(
        "productos/id/<int:id>", producto_view.detalle_producto, name="detalle_producto"
    ),
    path(
        "registro_empleado/", usuario_view.registro_empleado, name="registro_empleado"
    ),
    path(
        "trueques_entrantes/",
        trueque_view.trueques_entrantes,
        name="trueques_entrantes",
    ),
    path(
        "aceptar-solicitud/<int:trueque_id>/",
        trueque_view.aceptar_solicitud,
        name="aceptar-solicitud",
    ),
    path(
        "rechazar-solicitud-interes/<int:trueque_id>/",
        trueque_view.rechazar_solicitud_interes,
        name="rechazar-solicitud-interes",
    ),
    path(
        "rechazar-solicitud-horario/<int:trueque_id>/",
        trueque_view.rechazar_solitud_horario,
        name="rechazar-solicitud-horario",
    ),
    path(
        "rechazar-solicitud-fecha/<int:trueque_id>/",
        trueque_view.rechazar_solicitud_fecha,
        name="rechazar-solicitud-fecha",
    ),
    path(
        "rechazar-solicitud-otros/<int:trueque_id>/",
        trueque_view.rechazar_solicitud_otros,
        name="rechazar-solicitud-otros",
    ),
    path(
        "cancelar_trueque/<int:id>/<int:estado>/<str:ret>",
        trueque_view.cancelar_trueque,
        name="cancelar_trueque",
    ),
    path("solicitar/<int:id>/", trueque_view.solicitar, name="solicitar"),
    path("trueque/id/<int:id>", trueque_view.detalle_trueque, name="detalle_trueque"),
    path(
        "trueques_salientes/",
        trueque_view.trueques_salientes,
        name="trueques_salientes",
    ),
    path(
        "trueques_por_concretar/",
        trueque_view.trueques_por_concretar,
        name="trueques_por_concretar",
    ),
    path(
        "trueques_finalizados/",
        trueque_view.trueques_finalizados,
        name="trueques_finalizados",
    ),
    path("productos/id/<int:id>/preguntar", producto_view.preguntar, name="preguntar"),
    path("productos/id/<int:id>/responder", producto_view.responder, name="responder"),
    path(
        "filtrar_productos/<int:categoria>",
        producto_view.filtrar_productos,
        name="filtrar_productos",
    ),
    path("mis_productos/<int:id>", producto_view.mis_productos, name="mis_productos"),
    path("empleados", usuario_view.listado_empleados, name="empleados"),
    path(
        "trueques_programados/",
        trueque_view.trueques_programados,
        name="trueques_programados",
    ),
    path(
        "trueques_concretados/",
        trueque_view.trueques_concretados,
        name="trueques_concretados",
    ),
    path(
        "registrar-ventas/<int:trueque_id>",
        venta_view.registrar_ventas,
        name="registrar_ventas",
    ),
    path(
        "concretar-trueque/<int:trueque_id>/",
        trueque_view.confirmar_trueque,
        name="concretar_trueque",
    ),
    path(
        "listar-ventas-trueque/<int:trueque_id>",
        venta_view.listar_ventas,
        name="listar_ventas_trueque",
    ),
    path(
        "cancelar-trueques-programados/",
        trueque_view.cancelar_trueque_programado,
        name="cancelar_trueques_programados",
    ),
    path("sucursales/", sucursal_view.listado_sucursales, name="sucursales"),
    path(
        "promocionar-producto/<int:id>",
        producto_view.promocionar,
        name="promocionar_producto",
    ),
    path(
        "modificar_empleado/<int:id>/",
        usuario_view.modificar_empleado,
        name="modificar_empleado",
    ),
    path(
        "eliminar_empleado/<int:id>/",
        usuario_view.eliminar_empleado,
        name="eliminar_empleado",
    ),
    path("crear-sucursal/", sucursal_view.crear_sucursal, name="crear_sucursal"),
    path(
        "modificar_sucursal/<int:id>/",
        sucursal_view.modificar_sucursal,
        name="modificar_sucursal",
    ),
    path(
        "eliminar_sucursal/<int:id>/",
        sucursal_view.eliminar_sucursal,
        name="eliminar_sucursal",
    ),
    path(
        "generar_estadisticas_ventas",
        estadistica_view.generar_estadisticas_ventas,
        name="generar_estadisticas_ventas",
    ),
    path(
        "generar_estadisticas_trueques",
        estadistica_view.generar_estadisticas_trueques,
        name="generar_estadisticas_trueques",
    ),
]

tt_app/models.py
from django.db import models
from django.db.models.fields.files import ImageField
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from datetime import datetime


# Create your models here.
# Creating users and superusers


# Modelo de sucursal
class Sucursal(models.Model):
    ciudad = models.CharField(max_length=50)
    direccion = models.CharField(max_length=200)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.ciudad + " - " + self.direccion


class MyCustomUserManager(BaseUserManager):
    def create_cliente(
        self, email, first_name, last_name, dni, phone, birthdate, password=None
    ):
        if not email:
            raise ValueError("El nombre de usuario debe ser tu correo electrónico.")
        cliente = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            dni=dni,
            phone=phone,
            birthdate=birthdate,
        )
        cliente.set_password(password)
        cliente.save(using=self._db)
        return cliente

    def create_empleado(self, email, first_name, last_name, password, sucursal):
        if not email:
            raise ValueError("El nombre de usuario debe ser tu correo electrónico.")
        empleado = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            sucursal=sucursal,
        )
        empleado.is_staff = True
        empleado.set_password(password)
        empleado.save(using=self._db)
        return empleado

    def create_superuser(self, email, password):
        user = self.create_cliente(
            email=self.normalize_email(email),
            first_name="",
            last_name="",
            dni="",
            phone="",
            birthdate="1900-01-01",
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        # user.is_superuser = True #Comento esta línea porque no tendría que tener permitido el acceso al panel de administración de django
        user.save(using=self._db)
        return user


# User model
class Usuario(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, blank=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    dni = models.CharField(max_length=10, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    birthdate = models.DateField(default="1990-01-01", blank=True)
    hide_email = models.BooleanField(default=True)
    sucursal = models.ForeignKey(
        Sucursal, on_delete=models.CASCADE, related_name="empleados", null=True
    )

    objects = MyCustomUserManager()

    USERNAME_FIELD = "email"

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


# Product model
class Producto(models.Model):

    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(
        validators=[
            MinLengthValidator(10, "Este campo debe contener al menos 10 caracteres")
        ],
        max_length=1000,
    )

    class Categoria(models.IntegerChoices):
        categoria_1 = 1, _("$0-$4999")
        categoria_2 = 2, _("$5000-$9999")
        categoria_3 = 3, _("$10000+")

    categoria = models.IntegerField(choices=Categoria.choices)
    fecha_de_publicacion = models.DateTimeField(auto_now=False)

    imagen = ImageField(blank=True, upload_to="media/")
    promocionado = models.BooleanField(default=False)
    reservado = models.BooleanField(default=False)
    disponible = models.BooleanField(default=True)
    activo = models.BooleanField(default=True)
    usuario = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, related_name="productos"
    )
    sucursal = models.ForeignKey(
        Sucursal, on_delete=models.CASCADE, related_name="productos"
    )
    fecha_hasta_promocion = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.nombre + "\t(" + str(self.categoria) + ")"


# Modelo de trueque
class Trueque(models.Model):
    producto_solicitante = models.ForeignKey(
        Producto,
        on_delete=models.CASCADE,
        related_name="trueque",
        null=False,
        blank=False,
    )
    producto_solicitado = models.ForeignKey(
        Producto,
        on_delete=models.CASCADE,
        related_name="trueque_solicitado",
        null=False,
        blank=False,
    )
    sucursal = models.ForeignKey(
        Sucursal,
        on_delete=models.CASCADE,
        related_name="trueques",
        null=False,
        blank=False,
    )
    activo = models.BooleanField(default=True)
    fecha = models.DateField(auto_now=True)
    fecha_programada = models.DateField(default="2025-01-01", blank=True)

    class Rango_Horario(models.IntegerChoices):
        rango_1 = 1, _("Turno Mañana: 8 AM")
        rango_2 = 2, _("Turno Mañana: 9 AM")
        rango_3 = 3, _("Turno Mañana: 10 AM")
        rango_4 = 4, _("Turno Mañana: 11 AM")
        rango_5 = 5, _("Turno Tarde: 3 PM")
        rango_6 = 6, _("Turno Tarde: 4 PM")
        rango_7 = 7, _("Turno Tarde: 5 PM")
        rango_8 = 8, _("Turno Tarde: 6 PM")
        rango_9 = 9, _("Turno Tarde: 7 PM")

    horario = models.IntegerField(
        choices=Rango_Horario.choices, blank=False, null=False, default=1
    )

    class Estado(models.IntegerChoices):
        estado_1 = 1, _("Solicitado")
        estado_2 = 2, _("Pendiente")
        estado_3 = 3, _("Aceptado")
        estado_4 = 4, _("Concretado")
        estado_5 = 5, _("Rechazado")
        estado_6 = 6, _("Cancelado por empleado")
        estado_7 = 7, _("Cancelado por solicitante")
        estado_8 = 8, _("Cancelado por solicitado")
        estado_9 = 9, _("Concretó otro trueque")

    estado = models.IntegerField(choices=Estado.choices, default=1)

    class OpcionRechazo(models.IntegerChoices):
        rechazo_1 = 1, _("Producto ya no disponible")
        rechazo_2 = 2, _("Falta de interés en el producto ofrecido")
        rechazo_3 = 3, _("Falta de disponibilidad en el horario solicitado")
        rechazo_4 = 4, _("Falta de disponibilidad en la fecha solicitada")
        rechazo_5 = 5, _("Otros motivos")

    motivo_rechazo = models.IntegerField(
        choices=OpcionRechazo.choices, blank=True, null=True, default=None
    )

    def __str__(self):
        p1 = self.producto_solicitante
        p2 = self.producto_solicitado
        return (
            "("
            + str(self.id)
            + ")  "
            + p1.usuario.first_name
            + " quiere intercambiar "
            + p1.nombre
            + " por "
            + p2.nombre
            + " de "
            + p2.usuario.first_name
        )


# Modelo de respuesta
class Respuesta(models.Model):
    texto = models.CharField(max_length=200)
    fecha = models.DateField(auto_now=True)
    activo = models.BooleanField(default=True)


# Modelo de pregunta
class Pregunta(models.Model):
    producto = models.ForeignKey(
        Producto, on_delete=models.CASCADE, related_name="preguntas"
    )
    cliente = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    respuesta = models.ForeignKey(Respuesta, on_delete=models.CASCADE, null=True)
    fecha = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)


# Modelo de venta
class Venta(models.Model):
    cantidad_unidades = models.IntegerField()
    precio_unitario = models.FloatField()
    nombre_producto = models.CharField(max_length=200)
    trueque = models.ForeignKey(
        Trueque, on_delete=models.CASCADE, blank=True, null=True
    )
    vendedor = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, blank=True, null=True
    )
    fecha = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)

    def get_total(self):
        return self.cantidad_unidades * self.precio_unitario

tt_app/views/sucursal_view.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from ..forms.sucursal_forms import CrearSucursal
from ..forms.usuario_forms import check_cliente, check_empleado, check_administrador
from ..models import Sucursal
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import get_object_or_404


def listado_sucursales(request):
    sucursales = Sucursal.objects.filter(activo=True)
    return render(request, "sucursales/sucursales.html", {"sucursales": sucursales})


def crear_sucursal(request):
    chk = check_administrador(request.user)
    if chk["ok"]:
        return chk["return"]
    if request.POST:
        form = CrearSucursal(request.POST)
        if form.is_valid():
            sucursal = form.save(commit=False)
            # sucursal.ciudad = sucursal.ciudad.capitalize()
            sucursal.save()  # guardamos el producto
            # Redirigir a la página de productos con mensaje de feedback
            return redirect(
                reverse("sucursales")
                + "?mensaje=La sucursal se ha agregado correctamente."
            )
    else:
        form = CrearSucursal()
    return render(
        request,
        "sucursales/crear_sucursal.html",
        {  # enviamos los siguientes parámetros:
            "form": form,  # el form definido en producto_forms.py
            "titulo": "Registrar sucursal",  # el titulo del form
            "boton": "Aceptar",  # el texto del botón de confirmación
            "obligatorios": True,  # mostrar la advertencia de campos obligatorios o no
        },
    )


@login_required
def modificar_sucursal(request, id):
    chk = check_administrador(request.user)
    if chk["ok"]:
        return chk["return"]

    sucursal = get_object_or_404(Sucursal, id=id)

    if request.method == "POST":
        form = CrearSucursal(request.POST, request.FILES, instance=sucursal)
        if form.is_valid():
            form = form.save(commit=False)
            print("modificando...")
            form.save()
            # Redirigir a la página de las sucursales con mensaje de feedback
            return redirect(
                reverse("sucursales")
                + "?mensaje=La sucursal se ha modificado correctamente."
            )
    else:
        form = CrearSucursal(instance=sucursal)

    return render(
        request,
        "sucursales/crear_sucursal.html",
        {
            "form": form,
            "titulo": "Modificar sucursal",
            "boton": "Modificar",
            "obligatorios": False,
        },
    )


@login_required
def eliminar_sucursal(request, id):
    chk = check_administrador(request.user)
    if chk["ok"]:
        return chk["return"]

    sucursal = get_object_or_404(Sucursal, id=id)

    if request.method == "POST":
        sucursal.activo = False
        sucursal.save()
        return redirect(
            reverse("sucursales")
            + "?mensaje=La sucursal se ha eliminado correctamente."
        )
    else:
        # Redirigir a la página de las sucursales con mensaje de feedback
        return redirect(
            reverse("sucursales") + "?mensaje=La sucursal no se ha podido eliminar."
        )

tt_app/templates/productos/buscar_productos.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if productos %}
<h3 class="ms-4 mt-3 mb-5 text-start">Resultados de su búsqueda "{{cadena}}": </h3>
{% include 'productos/partials/filtros+listado.html' %}

{% else %}
    <h5 class="mt-5 my-3 text-center">No hay productos que contengan "{{cadena}}" en su título o descripción.</h5> 
    <p class="p-2 text-center"><a href="{%url 'productos'%}">Volver a productos</a></p>
{% endif %}

{%endblock%}

tt_app/templates/productos/crear_producto.html
{% extends 'base.html' %}

{% block content %}

{% include 'partials/form_vista.html'%}

{% endblock %}

tt_app/templates/productos/detalle_producto.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="card ">
{% if producto.activo %}

<div class="row m-4">
    <span class="d-flex align-items-center mb-4 ">
        <h3 class="me-3">{{producto.nombre|capfirst}}</h3> 
        <div class="mx-2">
            <a href="#" class="badge badge-primary bg-primary text-decoration-none text-white me-1">Categoria {{producto.get_categoria_display}}</a>{#LINK A BUSQUEDA FILTRADA #}

            {% if producto.promocionado %}

                <a href="#" class="badge badge-primary bg-warning text-decoration-none text-dark">Promocionado</a>{#LINK A HU PROMOCIONAR UN PRODUCTO #}
            {% else %}

                <a href="#" class="badge badge-secondary bg-secondary text-decoration-none text-white">No promocionado</a>{#LINK A HU PROMOCIONAR UN PRODUCTO #}
            {% endif %}
        </div>
    </span>
    <div class="col-5 ">
        <div class="d-flex align-items-center justify-content-center w-100">
            {% if producto.imagen %}
            <img src="{{producto.imagen.url}}" alt="Imagen del producto" class="img-fluid border border-2 w-100" />
            {% else %}
            <img src="{%static 'images/default-image-missing.png'%}" alt="El producto no tiene imagenes" class="img-thumbnail" />
            {% endif %}
        </div>
    </div>
    <div class="col-7 d-flex flex-column ps-4 pe-0">
        <span class="d-flex mb-4">
            <div class=" fw-light">
                <small>Sucursal del intercambio: {{producto.sucursal.ciudad}} - {{producto.sucursal.direccion}}</small><br>
                <small>Publicado por: {{producto.usuario.first_name}}</small><br>
                <small>Fecha de publicación: {{producto.fecha_de_publicacion|date:'l j \d\e F \d\e Y'|capfirst}} </small><br>
            </div>
            {%if not user.is_staff and producto.usuario != user and producto.disponible%}
                {%if not user.is_authenticated or producto.reservado%}
                <div class="d-flex flex-column justify-content-end align-items-center mb-auto ms-auto">
                    <button class="btn btn-secondary btn-lg" disabled>Solicitar intercambio</button>
                    {%if not user.is_authenticated%}
                    <small class="fw-light text-muted text-wrap opacity-75">Debes registrarte para hacer solicitudes.</small>
                    {%elif producto.reservado%}
                    <small class="fw-light text-muted text-wrap opacity-75">Este producto está reservado de momento.</small>
                    {%endif%}
                </div>
            {%else%}
            <a href="{% url 'solicitar' id=producto.id %}" class="btn btn-primary btn-lg mb-auto ms-auto">Solicitar intercambio</a>
            {%endif%}
            {%endif%}
        </span>
        <p class="mt-1">{{producto.descripcion|capfirst}}</p>
        
    </div>
    <h4 class="mt-5 mb-4">Preguntas y respuestas</h4>
    {% if user.is_authenticated %}
        {% if not user == producto.usuario and not user.is_staff%}
            <form action="{% url 'preguntar' producto.id %}" method="POST" class="d-flex flex-column" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {% for field in form_pregunta %} 
                    {{ field }}
                    {% if field.errors %}
                        {% for error in field.errors %}
                        <small class="text-danger fw-medium"><p>{{ error }}</p></small> {#errores de los campos#}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
                {%if error%}<small class="text-danger fw-medium my-1"><p>{{error}}</p></small>{%endif%}     {#errores del formulario entero#}
                <button class="btn btn-info fw-medium mt-2 ms-auto" type="submit">Preguntar</button>
            </form>
        {% endif %}
    {% endif %}
    {%if preguntas%}
    {% with preguntas.count as total_de_preguntas %}
        <h6 class="mt-4">
            {{ total_de_preguntas }} pregunta{{ total_de_preguntas|pluralize }}
        </h6>
    {% endwith %}
    {%endif%}
    {% for pregunta in preguntas.all %}
        <div class="preguntas card card-body mt-2">
            <p class="info text-muted"><b>{{ pregunta.cliente.first_name }}</b> <small>- {{pregunta.fecha|date:'j/n/y \a \l\a\s H:i'}}</small></p>
            <p class="mb-3">{{ pregunta.texto|capfirst}}</p>
            {% if pregunta.respuesta %}
                <div class="mx-3 text-muted">{{ pregunta.respuesta.texto|capfirst}}</div>
            {% else %}
                {% if user == producto.usuario and not user.is_staff%}
                    <form action="{% url 'responder' pregunta.id %}" method="POST" class="d-flex flex-column" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        {% for field in form_respuesta %} 
                            {{ field }}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                <small class="text-danger fw-medium"><p>{{ error }}</p></small>{#errores de los campos#}
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                        {%if error%}<small class="text-danger fw-medium my-1"><p>{{error}}</p></small>{%endif%}{#errores del formulario entero#}
                        <button class="btn btn-info fw-medium mt-2 ms-auto" type="submit">Responder</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
        {% empty %}
            <p class="text-muted">No hay preguntas</p>
    {% endfor %}
</div>
</div>
{% else %}
<h5 class=" p-6 text-center">
    Este producto ya no se encuentra disponible.
</h5> 
<p class=" p-2 text-center">
    <a href="{%url 'home'%}">Volver al inicio</a>
</p>
{% endif %}

{% endblock %}

tt_app/templates/productos/filtrar_productos.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if productos %}
    <h3 class="ms-4 mt-3 mb-5 text-start">Productos de categoría {{categoria}}:</h3>
    {% include 'productos/partials/filtrado_productos.html' %}
    <p class="p-2 text-center"><a href="{%url 'productos'%}">Volver a productos</a></p>
{% else %}
    <h5 class="mt-5 my-3 text-center">No hay productos de la categoría seleccionada.</h5> 
    <p class="p-2 text-center"><a href="{%url 'productos'%}">Volver a productos</a></p>
{% endif %}

{%endblock%}

tt_app/templates/productos/productos.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if productos %} 
<h3 class="ms-4 mt-3 mb-5 text-start ">Se muestran todos los productos: </h3>
{% include 'productos/partials/filtros+listado.html' %}

{% else %}
    <h5 class="mt-5 my-3 text-center">No hay productos cargados aún.</h5> 
    <p class="p-2 text-center"><a href="{%url 'home'%}">Volver al inicio</a></p>
{% endif %}

{%endblock%}

tt_app/templates/productos/promocionar.html
{% extends 'base.html' %}

{% block content %}

{% include 'partials/form_vista.html'%}

{% endblock %}